import BadgeIcon from '@/assets/badge.svg?react';
import BorderBadgeIcon from '@/assets/border-badge.svg?react';
import BorderCircleIcon from '@/assets/border-circle.svg?react';
import {
  Activity,
  AlertTriangle,
  Award,
  BadgeCheck,
  Ban,
  BatteryLow,
  Bell,
  BellOff,
  Book,
  BookOpen,
  Brain,
  Bug,
  CalendarCheck2,
  Camera,
  Check,
  CheckCircle2,
  CloudLightning,
  CloudRain,
  Code2,
  Coffee,
  Compass,
  Crown,
  Flame,
  Frown,
  Gift,
  Globe,
  Handshake,
  Heart,
  HeartCrack,
  HeartOff,
  Leaf,
  Medal,
  Moon,
  Rocket,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  Skull,
  Smile,
  Star,
  Sun,
  Tags,
  Target,
  TargetIcon,
  ThumbsUp,
  TrendingDown,
  TrendingUp,
  UserCheck,
  Users,
  X,
  XCircle,
  Zap
} from 'lucide-react';
import { BiSolidChevronDownCircle, BiSolidChevronsDown, BiSolidChevronsUp, BiSolidChevronUpCircle, BiSolidCrown } from 'react-icons/bi';
import { BsArrowThroughHeartFill, BsAwardFill, BsBroadcast, BsFillDiamondFill, BsHearts, BsHeptagonFill, BsLightningFill, BsOctagonFill, BsPentagonFill, BsXDiamondFill } from 'react-icons/bs';
import {
  FaAward,
  FaBell,
  FaCircleArrowUp,
  FaCloud,
  FaCloudSun,
  FaCrosshairs,
  FaCrown,
  FaEye,
  FaFeatherPointed,
  FaFlag,
  FaGear,
  FaGears,
  FaGift,
  FaGlobe,
  FaHandsHolding,
  FaHeart,
  FaJetFighter,
  FaLeaf,
  FaMap,
  FaMapLocationDot,
  FaMapPin,
  FaMountainSun,
  FaRibbon,
  FaRocket,
  FaShield,
  FaSkullCrossbones,
  FaSun,
  FaTags
} from 'react-icons/fa6';
import {
  GiAbstract016,
  GiAbstract069,
  GiAchievement,
  GiAmericanShield,
  GiAngelWings,
  GiArcheryTarget,
  GiArmorUpgrade,
  GiBigDiamondRing,
  GiBoltShield,
  GiBurningEmbers,
  GiCardboardBox,
  GiCheckedShield,
  GiCircle,
  GiCircleSparks,
  GiCondorEmblem,
  GiCrenulatedShield,
  GiCrossedBones,
  GiCrossedSwords,
  GiCrownedHeart,
  GiCrownedSkull,
  GiCrystalBall,
  GiCutDiamond,
  GiDiamondTrophy,
  GiEruption,
  GiFalloutShelter,
  GiFinishLine,
  GiFist,
  GiFlame,
  GiFlamedLeaf,
  GiFlowerEmblem,
  GiFlyingFlag,
  GiGearHammer,
  GiHeartburn,
  GiLaurelCrown as GiLaurel,
  GiLaurelCrown,
  GiLaurels,
  GiLaurelsTrophy,
  GiMedal,
  GiMuscleUp,
  GiPartyPopper,
  GiPlainCircle,
  GiPodiumWinner,
  GiPoliceBadge,
  GiGiftOfKnowledge as GiPresent,
  GiProgression,
  GiQueenCrown,
  GiRailRoad,
  GiRank1,
  GiRank2,
  GiRank3,
  GiRibbon,
  GiRibbonMedal,
  GiRibbonShield,
  GiRoad,
  GiRollingBomb,
  GiRoundStar,
  GiRupee,
  GiSevenPointedStar,
  GiShield,
  GiShieldEchoes,
  GiSkullRing,
  GiSkullShield,
  GiSlashedShield,
  GiSmallFire,
  GiSparkles,
  GiSparkSpirit,
  GiSportMedal,
  GiStack,
  GiStarFormation,
  GiStarMedal,
  GiStarsStack,
  GiStaryu,
  GiSteelwingEmblem,
  GiStripedSun,
  GiSundial,
  GiSwordsEmblem,
  GiTargetPrize,
  GiTreasureMap,
  GiTribalShield,
  GiTrophyCup,
  GiUpCard,
  GiUpgrade,
  GiVerticalBanner,
  GiVibratingShield,
  GiWeightLiftingUp,
  GiWildfires,
  GiWingedEmblem,
  GiWingedShield
} from 'react-icons/gi';
import { ImShield } from 'react-icons/im';
import { IoMdPin } from 'react-icons/io';
import { IoSparklesSharp } from 'react-icons/io5';
import { PiFlagCheckered, PiSunHorizonFill } from 'react-icons/pi';
import { RiVipDiamondFill } from 'react-icons/ri';
import { TbBadgeFilled, TbSquareRoundedChevronsDownFilled, TbSquareRoundedChevronsUpFilled } from 'react-icons/tb';

// Map style to shape icon (background container)
export const achievementBadgeStyles = {
  trophy: GiTrophyCup,
  star: GiRoundStar,
  star_formation: GiStarFormation,
  star_stack: GiStarsStack,
  point_star: GiSevenPointedStar,
  staryu: GiStaryu,
  ribbon_medal: GiRibbonMedal,
  knowledge: GiPresent,
  gift: FaGift,
  box: GiCardboardBox,
  circle: GiCircle,
  plain_circle: GiPlainCircle,
  border_circle: BorderCircleIcon,
  spark_circle: GiCircleSparks,
  abstract_circle: GiAbstract016,
  circles: GiAbstract069,
  badge: BadgeIcon,
  border_badge: BorderBadgeIcon,
  heptogon_badge: BsHeptagonFill,
  octagon_badge: BsOctagonFill,
  pentagon_badge: BsPentagonFill,
  laurel: GiLaurels,
  laurel_crown: GiLaurelCrown,
  laurel_trophy: GiLaurelsTrophy,
  crown: FaCrown,
  solid_crown: BiSolidCrown,
  skull_crown: GiCrownedSkull,
  heart_crown: GiCrownedHeart,
  queen_crown: GiQueenCrown,
  party: GiPartyPopper,
  hands: FaHandsHolding,
  shield: FaShield,
  star_shield: GiAmericanShield,
  bolt_shield: GiBoltShield,
  police_shield: GiPoliceBadge,
  ribbon_shield: GiRibbonShield,
  skull_shield: GiSkullShield,
  echo_shield: GiShieldEchoes,
  narrow_shield: GiShield,
  tribal_shield: GiTribalShield,
  slash_shield: GiSlashedShield,
  wing_shield: GiWingedShield,
  vibrating_shield: GiVibratingShield,
  checked_shield: GiCheckedShield,
  castle_shield: GiCrenulatedShield,
  sword_shield: GiSwordsEmblem,
  chevron_shield: ImShield,
  upgrade_shield: GiArmorUpgrade,
  medal: GiMedal,
  star_medal: GiStarMedal,
  sports_medal: GiSportMedal,
  award: FaAward,
  award_fill: BsAwardFill,
  award_wings: GiWingedEmblem,
  ribbon: FaRibbon,
  torn_ribbon: GiRibbon,
  achievement: GiAchievement,
  target: TargetIcon,
  archer_target: GiArcheryTarget,
  crosshairs: FaCrosshairs,
  road: GiRoad,
  railroad: GiRailRoad,
  map: FaMap,
  map_location: FaMapLocationDot,
  treasure_map: GiTreasureMap,
  diamond: GiCutDiamond,
  solid_diamond: RiVipDiamondFill,
  x_diamond: BsXDiamondFill,
  filled_diamond: BsFillDiamondFill,
  rupee: GiRupee,
  broadcast: BsBroadcast,
  angel: GiAngelWings,
  wings: GiSteelwingEmblem,
  ring: GiBigDiamondRing,
  skull_ring: GiSkullRing,
  fire: GiSmallFire,
  fires: GiWildfires,
  flame: GiFlame,
  flamed: GiFlamedLeaf,
  burning: GiBurningEmbers,
  sparkles: GiSparkles,
  spirit: GiSparkSpirit,
  lightning: BsLightningFill,
  banner: TbBadgeFilled,
  fancy_banner: GiVerticalBanner,
  flag: GiFlyingFlag,
  pin: FaMapPin,
  map_pin: IoMdPin,
  finish_line: GiFinishLine,
  checkered_flag: PiFlagCheckered,
  flower: GiFlowerEmblem,
  condor: GiCondorEmblem,
  sun: FaSun,
  cloud: FaCloud,
  cloud_sun: FaCloudSun,
  globe: FaGlobe,
  mountain: FaMountainSun,
  sunrise: PiSunHorizonFill,
  striped_sun: GiStripedSun,
  sundial: GiSundial,
  bomb: GiRollingBomb,
  stack: GiStack,
  skull: FaSkullCrossbones,
  crossbones: GiCrossedBones,
  crosssed_swords: GiCrossedSwords,
  fist: GiFist,
  heart: FaHeart,
  hearts: BsHearts,
  heart_arrow: BsArrowThroughHeartFill,
  heart_flame: GiHeartburn,
  circle_arrow: FaCircleArrowUp,
  feather: FaFeatherPointed,
  leaf: FaLeaf,
  rank1: GiRank1,
  rank2: GiRank2,
  rank3: GiRank3,
  bell: FaBell,
  gear: FaGear,
  gears: FaGears,
  hammer_gear: GiGearHammer,
  fallout: GiFalloutShelter,
  rocket: FaRocket,
  tag: FaTags,
  muscle_up: GiMuscleUp,
  up_card: GiUpCard,
  eruption: GiEruption,
  upgrade: GiUpgrade,
  weight_lifting: GiWeightLiftingUp,
  chevron_up: BiSolidChevronsUp,
  chevron_down: BiSolidChevronsDown,
  chevron_badge_up: TbSquareRoundedChevronsUpFilled,
  chevron_badge_down: TbSquareRoundedChevronsDownFilled,
};

export type AchievementBadgeStyle = keyof typeof achievementBadgeStyles;

// Map icon to center icon (content)
export const achievementBadgeIcons = {
  activity: Activity,
  alert: AlertTriangle,
  trophy: GiTrophyCup,
  star: Star,
  ribbon: GiRibbonMedal,
  present: Gift,
  box: GiCardboardBox,
  laurel: GiLaurel,
  podium: GiPodiumWinner,
  laurels: GiLaurels,
  party: GiPartyPopper,
  award: Award,
  badge: BadgeCheck,
  medal: Medal,
  target: Target,
  sparkles: IoSparklesSharp,
  users: Users,
  check: Check,
  check_circle: CheckCircle2,
  calendar: CalendarCheck2,
  book: Book,
  brain: Brain,
  compass: Compass,
  camera: Camera,
  coffee: Coffee,
  code: Code2,
  bell: Bell,
  bell_off: BellOff,
  cloud_rain: CloudRain,
  cloud_lightning: CloudLightning,
  battery_low: BatteryLow,
  ban: Ban,
  bug: Bug,
  frown: Frown,
  heart_crack: HeartCrack,
  heart_off: HeartOff,
  skull: Skull,
  x: X,
  x_circle: XCircle,
  flame: Flame,
  crown: Crown,
  rocket: Rocket,
  trending_up: TrendingUp,
  trending_down: TrendingDown,
  heart: Heart,
  smile: Smile,
  sun: Sun,
  moon: Moon,
  book_open: BookOpen,
  handshake: Handshake,
  globe: Globe,
  leaf: Leaf,
  shield: ShieldCheck,
  user: UserCheck,
  thumbs_up: ThumbsUp,
  zap: Zap,
  diamond: GiDiamondTrophy,
  achievement: GiAchievement,
  upgrade: GiUpgrade,
  progression: GiProgression,
  crystal: GiCrystalBall,
  target_prize: GiTargetPrize,
  archery_target: GiArcheryTarget,
  stars: GiStarsStack,
  trend: TrendingUp,
  rank1: GiRank1,
  rank2: GiRank2,
  rank3: GiRank3,
  fire: GiSmallFire,
  fires: GiWildfires,
  burning: GiBurningEmbers,
  bomb: GiRollingBomb,
  skull_ring: GiSkullRing,
  skull_shield: GiSkullShield,
  crossbones: GiCrossedBones,
  crossed_swords: GiCrossedSwords,
  fallout: GiFalloutShelter,
  gear: FaGear,
  gears: FaGears,
  hammer_gear: GiGearHammer,
  map: FaMap,
  map_pin: FaMapPin,
  road: GiRoad,
  railroad: GiRailRoad,
  finish_line: GiFinishLine,
  checkered_flag: PiFlagCheckered,
  shield_alert: ShieldAlert,
  shield_off: ShieldOff,
  eye: FaEye,
  tags: Tags,
  flag: FaFlag,
  fighter_jet: FaJetFighter,
  muscle_up: GiMuscleUp,
  weight_lifting: GiWeightLiftingUp,
  chevron_up: BiSolidChevronsUp,
  chevron_down: BiSolidChevronsDown,
  chevron_circle_up: BiSolidChevronUpCircle,
  chevron_circle_down: BiSolidChevronDownCircle,
};

export type AchievementBadgeIcon = keyof typeof achievementBadgeIcons;


/**
 * {
 *  bg // Background shape color
 *  accent // Center icon and label accent color -- text color is also based on this
 *  label // Label/banner/ribbon background color
 *  border // Border overlay color
 * }
 */
export const achievementBadgeColors = {
  copper: {
    bg: '#d4a574',
    lighting: '#fff0d8',
    accent: '#8b4513',
    label: '#2d1810',
    border: '#a0522d',
  },
  bronze: {
    bg: '#ffb347',
    lighting: '#fff1bf',
    accent: '#ff6b00',
    label: '#5c3000',
    border: '#ff8c00',
  },
  silver: {
    bg: '#c0c0c0',
    lighting: '#ffffff',
    accent: '#707070',
    label: '#2a2a2a',
    border: '#909090',
  },
  gold: {
    bg: '#ffd700',
    lighting: '#fffbd9',
    accent: '#ffaa00',
    label: '#664400',
    border: '#ffc800',
  },
  platinum: {
    bg: '#2a2d35',
    lighting: '#dce6ff',
    accent: '#a8b5c7',
    label: '#e8ecf2',
    border: '#9ca8ba',
  },
  diamond: {
    bg: '#0f1a2e',
    lighting: '#8fd9ff',
    accent: '#00d4ff',
    label: '#f0f9ff',
    border: '#0ea5e9',
  },
  sapphire: {
    bg: '#4a90e2',
    lighting: '#b6e2ff',
    accent: '#0047ab',
    label: '#001a40',
    border: '#1e5ba8',
  },
  emerald: {
    bg: '#50c878',
    lighting: '#c9ffe6',
    accent: '#0f7d3f',
    label: '#0a3920',
    border: '#2d9e60',
  },
  amethyst: {
    bg: '#9966cc',
    lighting: '#f0ccff',
    accent: '#5b1f8c',
    label: '#2d0f46',
    border: '#7b3bb5',
  },
  ruby: {
    bg: '#e0115f',
    lighting: '#ff9ad2',
    accent: '#9e0039',
    label: '#4d001c',
    border: '#c41e3a',
  },
  turquoise: {
    bg: '#7fffd4',
    lighting: '#e6fff8',
    accent: '#40e0d0',
    label: '#004d4d',
    border: '#20c9c9',
  },
  rose_quartz: {
    bg: '#f66d9b',
    lighting: '#ffd3e6',
    accent: '#c9184a',
    label: '#5e0825',
    border: '#e05780',
  },
  jade: {
    bg: '#d4e157',
    lighting: '#fdffe0',
    accent: '#9ccc65',
    label: '#33691e',
    border: '#aed581',
  },
  topaz: {
    bg: '#fb923c',
    lighting: '#fff2c7',
    accent: '#ffea00',
    label: '#78350f',
    border: '#f97316',
  },
  obsidian: {
    bg: '#607d8b',
    lighting: '#e9f6ff',
    accent: '#263238',
    label: '#000000',
    border: '#455a64',
  },
  magic: {
    bg: '#d946ef',
    lighting: '#ffd1ff',
    accent: '#8b00ff',
    label: '#2d0066',
    border: '#a855f7',
  },
  angelic: {
    bg: '#ffc4e1',
    lighting: '#ffffff',
    accent: '#ff69b4',
    label: '#ffffff',
    border: '#ffd1dc',
  },
  celestial: { // synthwave
    bg: '#ff1493',
    lighting: '#ffb3ea',
    accent: '#4169e1',
    label: '#1a0d3d',
    border: '#6b7dff',
  },
  aether: { // cyberpunk neon
    bg: '#00ffff',
    lighting: '#d9ffff',
    accent: '#ff00ff',
    label: '#4d004d',
    border: '#ff1aff',
  },
  hellfire: {
    bg: '#ff2400',
    lighting: '#ffe1a3',
    accent: '#ffea00',
    label: '#4d1900',
    border: '#ffd700',
  },
  tranquility: {
    bg: '#5cb3ff',
    lighting: '#e0f4ff',
    accent: '#66cdaa',
    label: '#0d2d3f',
    border: '#7ec8e3',
  },
  eros: { // aka "fusion"
    bg: '#ff6b9d',
    lighting: '#ffd6e6',
    accent: '#ffb6c1',
    label: '#4d0d1f',
    border: '#ff85a8',
  },
  iridescent: {
    bg: '#fdd0f1',
    lighting: '#40ff81',
    accent: '#ff4081',
    label: '#33001a',
    border: '#651fff',
  },
  regal: {
    bg: '#ffe47a',
    lighting: '#fff9b6',
    accent: '#ffb300',
    label: '#1b1f4b',
    border: '#5160c4',
  },
  flame: {
    bg: '#ff9500',
    lighting: '#ffe8b3',
    accent: '#ffd700',
    label: '#4d3300',
    border: '#ffb900',
  },
  intense_flame: {
    bg: '#ff8000',
    lighting: '#ffe0ad',
    accent: '#ff4500',
    label: '#4d1900',
    border: '#ff6600',
  },
  raging_flame: {
    bg: '#ff6600',
    lighting: '#ffd7a6',
    accent: '#ff0000',
    label: '#330000',
    border: '#ff3300',
  },
  infernal_flame: {
    bg: '#ff4500',
    lighting: '#ffc49a',
    accent: '#cc0000',
    label: '#1a0000',
    border: '#e60000',
  },
  consuming_flame: {
    bg: '#ff1493',
    lighting: '#ffd1f2',
    accent: '#0044ff',
    label: '#00194d',
    border: '#0066ff',
  },
  legendary_flame: {
    bg: '#ff00ff',
    lighting: '#ffd1ff',
    accent: '#00ffff',
    label: '#004d4d',
    border: '#00e5e5',
  },
  mystic: {
    bg: '#5b1a8c',
    lighting: '#e4b3ff',
    accent: '#ffc0e9',
    label: '#ff69b4',
    border: '#d946ef',
  },
  cosmic: {
    bg: '#1a237e',
    lighting: '#b3bdff',
    accent: '#e1bee7',
    label: '#d20f9e',
    border: '#651fff',
  },
  fanatic: { // aka "passion"
    bg: '#ef4444',
    lighting: '#ffc7c7',
    accent: '#ffe599',
    label: '#7f1d1d',
    border: '#dc2626',
  },
  copper_medallion: {
    bg: '#e4a766',
    lighting: '#fff1d9',
    accent: '#e4a766',
    label: '#241b16',
    border: '#ffbf7a',
  },
  bronze_medallion: {
    bg: '#ffb347',
    lighting: '#fff2c7',
    accent: '#ffb347',
    label: '#22170f',
    border: '#ff9a1f',
  },
  silver_medallion: {
    bg: '#d2d7de',
    lighting: '#ffffff',
    accent: '#d2d7de',
    label: '#191d22',
    border: '#a6b0bb',
  },
  gold_medallion: {
    bg: '#ffe066',
    lighting: '#fffbd9',
    accent: '#ffe066',
    label: '#211b12',
    border: '#ffcf33',
  },
  platinum_medallion: {
    bg: '#d9e2f0',
    lighting: '#ffffff',
    accent: '#d9e2f0',
    label: '#171b20',
    border: '#a7b7cc',
  },
  diamond_medallion: {
    bg: '#33e6ff',
    lighting: '#dcfcff',
    accent: '#33e6ff',
    label: '#141c22',
    border: '#59caff',
  },
  magic_medallion: {
    bg: '#f06bff',
    lighting: '#ffd6ff',
    accent: '#f06bff',
    label: '#211625',
    border: '#d07bff',
  },
};

export type AchievementBadgeColor = keyof typeof achievementBadgeColors;

export const achievementBadgeSizes = {
  small: {
    container: 48,
    icon: 12,
    label: '0.8rem',
  },
  medium: {
    container: 80,
    icon: 20,
    label: '1.35rem',
  },
  large: {
    container: 120,
    icon: 30,
    label: '2.1rem',
  },
};

export type AchievementBadgeSize = keyof typeof achievementBadgeSizes;