import BadgeIcon from '@/assets/badge.svg?react';
import BorderBadgeIcon from '@/assets/border-badge.svg?react';
import BorderCircleIcon from '@/assets/border-circle.svg?react';
import {
  Award,
  BadgeCheck,
  BookOpen,
  CalendarCheck2,
  Check,
  CheckCircle2,
  Crown,
  Flame,
  Gift,
  Globe,
  Handshake,
  Heart,
  Leaf,
  Medal,
  Moon,
  Rocket,
  ShieldCheck,
  Smile,
  Sparkles,
  Star,
  Sun,
  Tags,
  Target,
  TargetIcon,
  ThumbsUp,
  TrendingUp,
  UserCheck,
  Users,
  Zap
} from 'lucide-react';
import { BiSolidCrown } from 'react-icons/bi';
import { BsArrowThroughHeartFill, BsAwardFill, BsBroadcast, BsFillDiamondFill, BsHearts, BsHeptagonFill, BsLightningFill, BsOctagonFill, BsPentagonFill, BsXDiamondFill } from 'react-icons/bs';
import {
  FaAward,
  FaBell,
  FaCircleArrowUp,
  FaCloud,
  FaCloudSun,
  FaCrosshairs,
  FaCrown,
  FaEye,
  FaFeatherPointed,
  FaGear,
  FaGears,
  FaGift,
  FaGlobe,
  FaHandsHolding,
  FaHeart,
  FaLeaf,
  FaMap,
  FaMapLocationDot,
  FaMapPin,
  FaMountainSun,
  FaRibbon,
  FaRocket,
  FaShield,
  FaSkullCrossbones,
  FaSun,
  FaTags
} from 'react-icons/fa6';
import {
  GiAbstract016,
  GiAbstract069,
  GiAchievement,
  GiAmericanShield,
  GiAngelWings,
  GiArcheryTarget,
  GiBigDiamondRing,
  GiBoltShield,
  GiBurningEmbers,
  GiCardboardBox,
  GiCheckedShield,
  GiCircle,
  GiCircleSparks,
  GiCondorEmblem,
  GiCrenulatedShield,
  GiCrossedBones,
  GiCrossedSwords,
  GiCrownedHeart,
  GiCrownedSkull,
  GiCrystalBall,
  GiCutDiamond,
  GiDiamondTrophy,
  GiFalloutShelter,
  GiFinishLine,
  GiFist,
  GiFlame,
  GiFlamedLeaf,
  GiFlowerEmblem,
  GiFlyingFlag,
  GiGearHammer,
  GiLaurelCrown as GiLaurel,
  GiLaurelCrown,
  GiLaurels,
  GiLaurelsTrophy,
  GiMedal,
  GiPartyPopper,
  GiPlainCircle,
  GiPodiumWinner,
  GiPoliceBadge,
  GiGiftOfKnowledge as GiPresent,
  GiProgression,
  GiQueenCrown,
  GiRailRoad,
  GiRank1,
  GiRank2,
  GiRank3,
  GiRibbon,
  GiRibbonMedal,
  GiRibbonShield,
  GiRoad,
  GiRollingBomb,
  GiRoundStar,
  GiSevenPointedStar,
  GiShield,
  GiShieldEchoes,
  GiSkullRing,
  GiSkullShield,
  GiSlashedShield,
  GiSmallFire,
  GiSparkles,
  GiSparkSpirit,
  GiSportMedal,
  GiStack,
  GiStarFormation,
  GiStarMedal,
  GiStarsStack,
  GiStaryu,
  GiSteelwingEmblem,
  GiStripedSun,
  GiSundial,
  GiSwordsEmblem,
  GiTargetPrize,
  GiTreasureMap,
  GiTribalShield,
  GiTrophyCup,
  GiUpgrade,
  GiVerticalBanner,
  GiVibratingShield,
  GiWildfires,
  GiWingedShield
} from 'react-icons/gi';
import { ImShield } from 'react-icons/im';
import { IoMdPin } from 'react-icons/io';
import { PiFlagCheckered, PiSunHorizonFill } from 'react-icons/pi';
import { RiVipDiamondFill } from 'react-icons/ri';
import { TbBadgeFilled } from 'react-icons/tb';

// Map style to shape icon (background container)
export const achievementBadgeStyles = {
  trophy: GiTrophyCup,
  star: GiRoundStar,
  star_formation: GiStarFormation,
  star_stack: GiStarsStack,
  point_star: GiSevenPointedStar,
  staryu: GiStaryu,
  ribbon_medal: GiRibbonMedal,
  knowledge: GiPresent,
  gift: FaGift,
  box: GiCardboardBox,
  circle: GiCircle,
  plain_circle: GiPlainCircle,
  border_circle: BorderCircleIcon,
  spark_circle: GiCircleSparks,
  abstract_circle: GiAbstract016,
  circles: GiAbstract069,
  badge: BadgeIcon,
  border_badge: BorderBadgeIcon,
  heptogon_badge: BsHeptagonFill,
  octagon_badge: BsOctagonFill,
  pentagon_badge: BsPentagonFill,
  laurel: GiLaurels,
  laurel_crown: GiLaurelCrown,
  laurel_trophy: GiLaurelsTrophy,
  crown: FaCrown,
  solid_crown: BiSolidCrown,
  skull_crown: GiCrownedSkull,
  heart_crown: GiCrownedHeart,
  queen_crown: GiQueenCrown,
  party: GiPartyPopper,
  hands: FaHandsHolding,
  shield: FaShield,
  star_shield: GiAmericanShield,
  bolt_shield: GiBoltShield,
  police_shield: GiPoliceBadge,
  ribbon_shield: GiRibbonShield,
  skull_shield: GiSkullShield,
  echo_shield: GiShieldEchoes,
  narrow_shield: GiShield,
  tribal_shield: GiTribalShield,
  slash_shield: GiSlashedShield,
  wing_shield: GiWingedShield,
  vibrating_shield: GiVibratingShield,
  checked_shield: GiCheckedShield,
  castle_shield: GiCrenulatedShield,
  sword_shield: GiSwordsEmblem,
  chevron_shielf: ImShield,
  medal: GiMedal,
  star_medal: GiStarMedal,
  sports_medal: GiSportMedal,
  award: FaAward,
  award_fill: BsAwardFill,
  ribbon: FaRibbon,
  torn_ribbon: GiRibbon,
  target: TargetIcon,
  archer_target: GiArcheryTarget,
  crosshairs: FaCrosshairs,
  road: GiRoad,
  railroad: GiRailRoad,
  map: FaMap,
  map_location: FaMapLocationDot,
  treasure_map: GiTreasureMap,
  diamond: GiCutDiamond,
  solid_diamond: RiVipDiamondFill,
  x_diamond: BsXDiamondFill,
  filled_diamond: BsFillDiamondFill,
  broadcast: BsBroadcast,
  angel: GiAngelWings,
  wings: GiSteelwingEmblem,
  ring: GiBigDiamondRing,
  skull_ring: GiSkullRing,
  fire: GiSmallFire,
  fires: GiWildfires,
  flame: GiFlame,
  flamed: GiFlamedLeaf,
  burning: GiBurningEmbers,
  sparkles: GiSparkles,
  spirit: GiSparkSpirit,
  lightning: BsLightningFill,
  banner: TbBadgeFilled,
  fancy_banner: GiVerticalBanner,
  flag: GiFlyingFlag,
  pin: FaMapPin,
  map_pin: IoMdPin,
  finish_line: GiFinishLine,
  checkered_flag: PiFlagCheckered,
  flower: GiFlowerEmblem,
  condor: GiCondorEmblem,
  sun: FaSun,
  cloud: FaCloud,
  cloud_sun: FaCloudSun,
  globe: FaGlobe,
  mountain: FaMountainSun,
  sunrise: PiSunHorizonFill,
  striped_sun: GiStripedSun,
  sundial: GiSundial,
  bomb: GiRollingBomb,
  stack: GiStack,
  skull: FaSkullCrossbones,
  crossbones: GiCrossedBones,
  crosssed_swords: GiCrossedSwords,
  fist: GiFist,
  heart: FaHeart,
  hearts: BsHearts,
  heart_arrow: BsArrowThroughHeartFill,
  circle_arrow: FaCircleArrowUp,
  feather: FaFeatherPointed,
  leaf: FaLeaf,
  rank1: GiRank1,
  rank2: GiRank2,
  rank3: GiRank3,
  bell: FaBell,
  gear: FaGear,
  gears: FaGears,
  hammer_gear: GiGearHammer,
  fallout: GiFalloutShelter,
  rocket: FaRocket,
  tag: FaTags,
};

export type AchievementBadgeStyle = keyof typeof achievementBadgeStyles;

// Map icon to center icon (content)
export const achievementBadgeIcons = {
  trophy: GiTrophyCup,
  star: Star,
  ribbon: GiRibbonMedal,
  present: Gift,
  box: GiCardboardBox,
  laurel: GiLaurel,
  podium: GiPodiumWinner,
  laurels: GiLaurels,
  party: GiPartyPopper,
  award: Award,
  badge: BadgeCheck,
  medal: Medal,
  target: Target,
  sparkles: Sparkles,
  users: Users,
  check: Check,
  checkCircle: CheckCircle2,
  calendar: CalendarCheck2,
  flame: Flame,
  crown: Crown,
  rocket: Rocket,
  trending: TrendingUp,
  heart: Heart,
  smile: Smile,
  sun: Sun,
  moon: Moon,
  book: BookOpen,
  handshake: Handshake,
  globe: Globe,
  leaf: Leaf,
  shield: ShieldCheck,
  user: UserCheck,
  thumbsUp: ThumbsUp,
  zap: Zap,
  diamond: GiDiamondTrophy,
  achievement: GiAchievement,
  upgrade: GiUpgrade,
  progression: GiProgression,
  crystal: GiCrystalBall,
  targetPrize: GiTargetPrize,
  stars: GiStarsStack,
  trend: TrendingUp,
  eye: FaEye,
  tags: Tags,
  flag: GiFlyingFlag,
};

export type AchievementBadgeIcon = keyof typeof achievementBadgeIcons;

export const achievementBadgeColors = {
  gold: {
    bg: '#ffe082',
    accent: '#ffd600',
    text: '#7c5c00',
    border: '#ffd600',
  },
  silver: {
    bg: '#e0e0e0',
    accent: '#bdbdbd',
    text: '#616161',
    border: '#bdbdbd',
  },
  bronze: {
    bg: '#ffcc80',
    accent: '#ff9800',
    text: '#7c4a00',
    border: '#ff9800',
  },
  blue: {
    bg: '#bbdefb',
    accent: '#1976d2',
    text: '#0d305a',
    border: '#1976d2',
  },
  green: {
    bg: '#c8e6c9',
    accent: '#388e3c',
    text: '#1b3c1b',
    border: '#388e3c',
  },
  purple: {
    bg: '#e1bee7',
    accent: '#8e24aa',
    text: '#3d1b4d',
    border: '#8e24aa',
  },
  red: {
    bg: '#ef9a9a',
    accent: '#c62828',
    text: '#7f1d1d',
    border: '#c62828',
  },
  teal: {
    bg: '#b2dfdb',
    accent: '#00796b',
    text: '#0d3734',
    border: '#00796b',
  },
  pink: {
    bg: '#f8bbd0',
    accent: '#c2185b',
    text: '#4d1335',
    border: '#c2185b',
  },
  cyan: {
    bg: '#b2ebf2',
    accent: '#0097a7',
    text: '#0d3740',
    border: '#0097a7',
  },
  synthwave: {
    bg: '#ff6ec4',
    accent: '#7873f5',
    text: '#3d1473',
    border: '#7873f5',
  },
  cyberpunk: {
    bg: '#0ff',
    accent: '#f0f',
    text: '#730073',
    border: '#f0f',
  },
  rage: {
    bg: '#ff3c00',
    accent: '#ffff00',
    text: '#733a00',
    border: '#ffff00',
  },
  tranquil: {
    bg: '#90caf9',
    accent: '#a5d6a7',
    text: '#1e3a5f',
    border: '#a5d6a7',  
  },
  fusion: {
    bg: '#ff9a9e',
    accent: '#fad0c4',
    text: '#5f2124',
    border: '#fad0c4',
  },
  dark: {
    bg: '#b0bec5',
    accent: '#455a64',
    text: '#263238',
    border: '#455a64',
  },
  magic: {
    bg: '#ce93d8',
    accent: '#7e57c2',
    text: '#311b92',
    border: '#7e57c2',
  },
  honor: {
    bg: '#f0f4c3',
    accent: '#c0ca33',
    text: '#4e5500',
    border: '#c0ca33',
  },
  scifi: {
    bg: '#81d4fa',
    accent: '#4fc3f7',
    text: '#015f7d',
    border: '#4fc3f7',
  },
  grounded: {
    bg: '#d7ccc8',
    accent: '#6d4c41',
    text: '#3e2723',
    border: '#6d4c41',
  }
};

export type AchievementBadgeColor = keyof typeof achievementBadgeColors;

export const achievementBadgeSizes = {
  small: {
    container: 48,
    icon: 22,
    label: '0.95rem',
  },
  medium: {
    container: 80,
    icon: 36,
    label: '1.35rem',
  },
  large: {
    container: 120,
    icon: 54,
    label: '2.1rem',
  },
};

export type AchievementBadgeSize = keyof typeof achievementBadgeSizes;