import type { Goal } from "@/features/db/localdb";

// Dummy goals
export const demoGoals = (datasetId: string): Goal[] => [
  {
    id: 'g1',
    datasetId: datasetId ?? '',
    createdAt: Date.now(),
    title: 'First Entry',
    description: 'Add your first number',
    badge: { style: 'medal', icon: 'star', color: 'gold', label: '1' },
    target: { condition: 'above', metric: 'count', source: 'stats', value: 1 },
    type: 'goal',
    timePeriod: 'anytime',
    count: 1,
  },
  {
    id: 'g2',
    datasetId: datasetId ?? '',
    createdAt: Date.now(),
    title: '7-Day Streak',
    description: 'Positive numbers for 7 days in a row',
    badge: { style: 'ribbon', icon: 'calendar', color: 'sapphire', label: '7' },
    target: { condition: 'above', metric: 'total', source: 'stats', value: 0 },
    type: 'goal',
    timePeriod: 'day',
    count: 7,
    consecutive: true,
  },
  {
    id: 'g3',
    datasetId: datasetId ?? '',
    createdAt: Date.now(),
    title: '100k Total',
    description: 'Reach 100,000 total',
    badge: { style: 'trophy', icon: 'trophy', color: 'gold', label: '100k' },
    target: { condition: 'above', metric: 'total', source: 'stats', value: 100000 },
    type: 'milestone',
    timePeriod: 'anytime',
    count: 1,
  },
  // Additional demo goals from examples
  {
    id: 'g4',
    datasetId: datasetId ?? '',
    createdAt: Date.now(),
    title: 'Active Month',
    description: 'Add a number any day this month',
    badge: { style: 'circle', icon: 'calendar', color: 'emerald', label: 'M' },
    target: { condition: 'above', metric: 'count', source: 'stats', value: 1 },
    type: 'goal',
    timePeriod: 'month',
    count: 1,
  },
  {
    id: 'g5',
    datasetId: datasetId ?? '',
    createdAt: Date.now(),
    title: '1k Monthly Target',
    description: 'Reach 1,000 in a month',
    badge: { style: 'border_badge', icon: 'target', color: 'sapphire', label: '1k' },
    target: { condition: 'above', metric: 'total', source: 'stats', value: 1000 },
    type: 'target',
    timePeriod: 'month',
    count: 1,
  },
  {
    id: 'g6',
    datasetId: datasetId ?? '',
    createdAt: Date.now(),
    title: 'Perfect Month',
    description: 'No zero days in a month',
    badge: { style: 'border_circle', icon: 'star', color: 'amethyst', label: '★' },
    target: { condition: 'above', metric: 'min', source: 'stats', value: 0 },
    type: 'goal',
    timePeriod: 'month',
    count: 1,
  },
  {
    id: 'g7',
    datasetId: datasetId ?? '',
    createdAt: Date.now(),
    title: '10% Weekly Target',
    description: 'Increase by 10% in a week',
    badge: { style: 'ribbon', icon: 'trend', color: 'ruby', label: '10%' },
    target: { condition: 'above', metric: 'total', source: 'percents', value: 10 },
    type: 'target',
    timePeriod: 'week',
    count: 1,
  },
  {
    id: 'g8',
    datasetId: datasetId ?? '',
    createdAt: Date.now(),
    title: '100 Positive Days',
    description: 'Log a positive number on 100 days',
    badge: { style: 'circle', icon: 'star', color: 'gold', label: '100' },
    target: { condition: 'above', metric: 'total', source: 'stats', value: 0 },
    type: 'goal',
    timePeriod: 'day',
    count: 100,
  },
  {
    id: 'g9',
    datasetId: datasetId ?? '',
    createdAt: Date.now(),
    title: '1k a Day Week',
    description: 'Log at least 1,000 each day for a week',
    badge: { style: 'trophy', icon: 'calendar', color: 'sapphire', label: '1k' },
    target: { condition: 'above', metric: 'total', source: 'stats', value: 1000 },
    type: 'goal',
    timePeriod: 'day',
    count: 7,
    consecutive: true
  },
  {
    id: 'g10',
    datasetId: datasetId ?? '',
    createdAt: Date.now(),
    title: '100% Daily Growth',
    description: 'Increase by 1%',
    badge: { style: 'border_badge', icon: 'trend', color: 'emerald', label: '100%' },
    target: { condition: 'above', metric: 'total', source: 'percents', value: 1 },
    type: 'goal',
    timePeriod: 'day',
    count: 1,
  }
];

  // Dummy milestones
  export const demoMilestones = (datasetId: string): Goal[] => [
  {
    id: 'm1',
    datasetId: datasetId ?? '',
    createdAt: Date.now(),
    title: 'First 10k',
    description: 'Reach 10,000 total',
    badge: { style: 'medal', icon: 'star', color: 'gold', label: '10k' },
    target: { condition: 'above', metric: 'total', source: 'stats', value: 10000 },
    type: 'milestone',
    timePeriod: 'anytime',
    count: 1,
  },
  {
    id: 'm2',
    datasetId: datasetId ?? '',
    createdAt: Date.now(),
    title: 'First 50k',
    description: 'Reach 50,000 total',
    badge: { style: 'trophy', icon: 'trophy', color: 'amethyst', label: '50k' },
    target: { condition: 'above', metric: 'total', source: 'stats', value: 50000 },
    type: 'milestone',
    timePeriod: 'anytime',
    count: 1,
  },
];

// Dummy targets (only in preview mode)
const demoTargets = (datasetId: string): Goal[] => [
  {
    id: 't1',
    datasetId: datasetId ?? '',
    createdAt: Date.now(),
    title: 'Weekly 5k',
    description: 'Hit 5,000 in a week',
    badge: { style: 'ribbon', icon: 'target', color: 'emerald', label: '5k' },
    target: { condition: 'above', metric: 'total', source: 'stats', value: 5000 },
    type: 'target',
    timePeriod: 'week',
    count: 1,
  },
  {
    id: 't2',
    datasetId: datasetId ?? '',
    createdAt: Date.now(),
    title: 'Monthly 20k',
    description: 'Hit 20,000 in a month',
    badge: { style: 'star', icon: 'calendar', color: 'sapphire', label: '20k' },
    target: { condition: 'above', metric: 'total', source: 'stats', value: 20000 },
    type: 'target',
    timePeriod: 'month',
    count: 1,
  },
  {
    id: 't3',
    datasetId: datasetId ?? '',
    createdAt: Date.now(),
    title: 'Monthly 5k',
    description: 'Hit 5,000 in a month',
    badge: { style: 'star', icon: 'calendar', color: 'sapphire', label: '5k' },
    target: { condition: 'above', metric: 'total', source: 'stats', value: 5000 },
    type: 'target',
    timePeriod: 'month',
    count: 1,
  },
  {
    id: 't4',
    datasetId: datasetId ?? '',
    createdAt: Date.now(),
    title: 'Daily 1k',
    description: 'Hit 1,000 in a day',
    badge: { style: 'star', icon: 'calendar', color: 'sapphire', label: '1k' },
    target: { condition: 'above', metric: 'total', source: 'stats', value: 1000 },
    type: 'target',
    timePeriod: 'day',
    count: 1,
  },
  {
    id: 't5',
    datasetId: datasetId ?? '',
    createdAt: Date.now(),
    title: 'Daily 200',
    description: 'Hit 200 in a day',
    badge: { style: 'trophy', icon: 'trophy', color: 'gold', label: '200' },
    target: { condition: 'above', metric: 'total', source: 'stats', value: 200 },
    type: 'target',
    timePeriod: 'day',
    count: 1,
  }
];